filebeat.inputs:
- type: log
  tags: [ 'ugc_likes_nginx' ]
  enabled: true
  paths:
    - /var/log/nginx/*
  json:
    keys_under_root: true
    add_error_key: true
output.logstash:
  enabled: true
  hosts: ["ugc2_logstash:5045"]