version: '3.8'

services:
  ugc2_mongo_db:
    image: mongo:4.4.20-rc0-focal
    restart: always
    expose:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
  ugc2_fastapi:
    build:
      context: ./ugc_fastapi
    image: ugcfastapi-image
    env_file:
      - ./.env
    container_name: ugcfastapi_container
    restart: unless-stopped
    networks:
      - movies_network

  ugc2_nginx:
    image: nginx:1.22.1
    container_name: nginx_container
    volumes:
      - ./db/mongo:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 5
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
      - ./tmp/logs/nginx/:/var/log/nginx/
    depends_on:
      - ugc2_fastapi
    ports:
      - "27017:27017"

  mongo_express_open_data:
    image: mongo-express:1.0.0-alpha
    restart: always
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ugc2_mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8081:8081"
#  fastapi:
#    build:
#      context: ./ugc_fastapi
#    image: ugcfastapi-image
#    env_file:
#      - ./.env
#    depends_on:
#      kafka-zookeeper:
#        condition: service_healthy
#
#    container_name: ugcfastapi_container
#    restart: unless-stopped
#
#  nginx:
#    image: nginx:1.22.1
#    container_name: nginx_container
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
#      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
#    depends_on:
#      - fastapi
#    ports:
#      - "443:443"
#      - "80:80"
#    restart: always
#
#volumes:
#  kafka_volume:
    networks:
      - movies_network

  ugc2_logstash:
    image: docker.elastic.co/logstash/logstash:7.17.6
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "ugc2-elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./elk/logstash/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf
    networks:
      - movies_network

  ugc2-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
    volumes:
      - ./tmp/esdata:/tmp/elasticsearch/data
    networks:
      - movies_network

  ugc2_kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    environment:
      ELASTICSEARCH_HOSTS: "http://ugc2-elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - ugc2-elasticsearch
    networks:
      - movies_network

  ugc2_filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.6
    volumes:
      - ./tmp/logs/nginx:/var/log/nginx:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - ugc2_fastapi
      - ugc2_nginx
      - ugc2_logstash
      - ugc2-elasticsearch
      - ugc2_kibana
    networks:
      - movies_network

volumes:
  kafka_volume:

networks:
  movies_network:
    external: true