version: '3.8'

services:
  fastapi:
    build:
      context: ./ugc_fastapi
    image: ugcfastapi-image
    env_file:
      - ./.env
    depends_on:
      kafka-zookeeper:
        condition: service_healthy

    container_name: ugcfastapi_container
    restart: unless-stopped

  nginx:
    image: nginx:1.22.1
    container_name: nginx_container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - fastapi
    ports:
      - "443:443"
      - "80:80"
    restart: always

volumes:
  kafka_volume: