version: '3.8'

services:
  ugc2_mongo_db:
    image: mongo:4.4.20-rc0-focal
    restart: always
    expose:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - ./db/mongo:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "27017:27017"
    networks:
      - movies_network

  mongo_express_open_data:
    image: mongo-express:1.0.0-alpha
    restart: always
    expose:
      - "8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ugc2_mongo_db
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8081:8081"
    networks:
      - movies_network

  ugc2_fastapi:
    build:
      context: ./ugc_fastapi
    image: ugc2_fastapi-image
    env_file:
      - ./.env
    container_name: ugc2_fastapi
    restart: unless-stopped
    depends_on:
      ugc2_logstash:
        condition: service_healthy
      ugc2_mongo_db:
        condition: service_healthy
    networks:
      - movies_network
    logging:
      driver: gelf
      options:
        gelf-address: udp://127.0.0.1:5044
        tag: "ugc_likes_app"

  ugc2_nginx:
    image: nginx:1.22.1
    container_name: nginx_container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
      - ./tmp/logs/nginx/:/var/log/nginx/
    depends_on:
      - ugc2_fastapi
    ports:
      - "80:80"
    networks:
      - movies_network

  ugc2_logstash:
    image: logstash:8.5.3
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "ugc2-elasticsearch:9200"
    ports:
      - "5044:5044/udp"
      - "5045:5045/udp"
    volumes:
      - ./elk/logstash/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:9600/_node/stats" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - movies_network

  ugc2-elasticsearch:
    image: elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - USE_SSL=false
    ports:
      - "9200:9200"
    volumes:
      - ./tmp/esdata:/tmp/elasticsearch/data
    networks:
      - movies_network

  ugc2_kibana:
    image: kibana:8.5.3
    environment:
      ELASTICSEARCH_HOSTS: "http://ugc2-elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - ugc2-elasticsearch
    networks:
      - movies_network

  ugc2_filebeat:
    image: elastic/filebeat:8.5.3
    volumes:
      - ./tmp/logs/nginx:/var/log/nginx:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - ugc2_fastapi
      - ugc2_nginx
      - ugc2_logstash
      - ugc2-elasticsearch
      - ugc2_kibana
    networks:
      - movies_network

networks:
  movies_network:
    external: true